fix(docker): copied lli
Signed-off-by: ShigrafS <shigrafsalik@proton.me>

diff --git a/utils/docker/Dockerfile.alpine-static b/utils/docker/Dockerfile.alpine-static
--- a/utils/docker/Dockerfile.alpine-static
+++ b/utils/docker/Dockerfile.alpine-static
@@ -52,6 +52,7 @@ RUN cmake -B build \
     llvm
 
 RUN cmake --build build --target install
+RUN test -f /lld-install/bin/lli || (echo "Error: lli not installed!" && false)
 
 ########################################
 # Stage 3: Alpine Static Image with LLD
@@ -115,6 +116,10 @@ RUN ! xx-info is-cross || cp -f /usr/bin/llvm-lto $(xx-info sysroot)/usr/bin/llv
 # LTO shared lib
 COPY --from=lld-builder /lld-install/lib/libLTO.so* /usr/lib/
 RUN ! xx-info is-cross || cp -f /usr/lib/libLTO.so* $(xx-info sysroot)/usr/lib/
+
+# llvm lli
+COPY --from=lld-builder /lld-install/bin/lli /usr/bin/
+RUN ! xx-info is-cross || cp -f /usr/bin/lli $(xx-info sysroot)/usr/bin/lli
 
 COPY --from=lld-builder /lld-install/bin/llvm-profdata /usr/bin/
 RUN ! xx-info is-cross || cp -f /usr/bin/llvm-profdata $(xx-info sysroot)/usr/bin/llvm-profdata
